name: reading-rating-dev
recipe: drupal10
config:
  webroot: web
  conf:
    php: php.ini
tooling:
  drush:
    service: appserver
    env:
      DRUSH_OPTIONS_URI: "https://reading-rating-dev.lndo.site"
